version: 2

jobs:
        build:
                working_directory: ~/app-build
                docker:
                        - image: circleci/node:lts
                steps:
                        - checkout

                        - restore_cache:
                                  key: dependency-cache-{{ checksum "package.json" }}

                        - run: sudo apt update && sudo apt install -y rsync
                        - run:
                                  name: install-npm-wee
                                  no_output_timeout: 30m
                                  command: npx yarn install
                        - run:
                                  name: build client
                                  no_output_timeout: 30m
                                  command: npx yarn run build

                        - save_cache:
                                  key: dependency-cache-{{ checksum "package.json" }}
                                  paths:
                                          - ./node_modules
                                          - ./client/node_modules
                                          - ./server/node_modules

                        - store_artifacts:
                                  path: report.xml
                        - store_artifacts:
                                  path: coverage
                        - store_test_results:
                                  path: test-results.xml
